modLoader = "javafml"
loaderVersion = "[10,)"
#issueTrackerURL = ""
license = "All Rights Reserved"

[[mods]]
modId = "craftcord"
version = "${version}"
displayName = "Craftcord"
authors = "PixelSam123, Mednoob"
description = "${description}"
#logoFile = ""

[[dependencies.craftcord]]
modId = "neoforge"
type = "required"
versionRange = "[21,)"
ordering = "NONE"
side = "SERVER"

[[dependencies.craftcord]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.11,)"
ordering = "NONE"
side = "SERVER"

[[dependencies.craftcord]]
modId = "architectury"
type = "required"
versionRange = "[19,)"
ordering = "AFTER"
side = "SERVER"

[[mixins]]
config = "craftcord.mixins.json"
